/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;


public class Principal extends javax.swing.JFrame {
private static Principal instancia;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btRequisicao = new javax.swing.JButton();
        btCotacao = new javax.swing.JButton();
        btEncomenda = new javax.swing.JButton();
        btCompra = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btProduto = new javax.swing.JButton();
        btUnidade = new javax.swing.JButton();
        btPessoa = new javax.swing.JButton();
        btFornecedor = new javax.swing.JButton();
        btEmbalagem = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cotacom");
        setForeground(java.awt.Color.lightGray);

        btRequisicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Requisi��o.png"))); // NOI18N
        btRequisicao.setText("Requisi��es");
        btRequisicao.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/requisi��o.png"))); // NOI18N
        btRequisicao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRequisicaoActionPerformed(evt);
            }
        });

        btCotacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Cota��o.png"))); // NOI18N
        btCotacao.setText("Cota��es");
        btCotacao.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/cota��o.png"))); // NOI18N
        btCotacao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCotacaoActionPerformed(evt);
            }
        });

        btEncomenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Encomenda.png"))); // NOI18N
        btEncomenda.setText("Encomendas");
        btEncomenda.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/encomenda.png"))); // NOI18N
        btEncomenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncomendaActionPerformed(evt);
            }
        });

        btCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Compra.png"))); // NOI18N
        btCompra.setText("Compras");
        btCompra.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/compra.png"))); // NOI18N
        btCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(btCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btEncomenda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRequisicao)
                    .addComponent(btCotacao)
                    .addComponent(btEncomenda))
                .addGap(18, 18, 18)
                .addComponent(btCompra)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lan�amentos", jPanel1);

        btProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Produto.png"))); // NOI18N
        btProduto.setText("Produtos");
        btProduto.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/produto.png"))); // NOI18N
        btProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutoActionPerformed(evt);
            }
        });

        btUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Unidade de Medida.png"))); // NOI18N
        btUnidade.setText("Unidades de Medida");
        btUnidade.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/unidade de medida.png"))); // NOI18N
        btUnidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnidadeActionPerformed(evt);
            }
        });

        btPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Pessoa.png"))); // NOI18N
        btPessoa.setText("Pessoas");
        btPessoa.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/pessoa.png"))); // NOI18N
        btPessoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPessoaActionPerformed(evt);
            }
        });

        btFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Fornecedor.png"))); // NOI18N
        btFornecedor.setText("Fornecedores");
        btFornecedor.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/fornecedor.png"))); // NOI18N
        btFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorActionPerformed(evt);
            }
        });

        btEmbalagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/Embalagem.png"))); // NOI18N
        btEmbalagem.setText("Embalagens");
        btEmbalagem.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/embalagem.png"))); // NOI18N
        btEmbalagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmbalagemActionPerformed(evt);
            }
        });

        btUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones/usuario.png"))); // NOI18N
        btUsuario.setText("Usu�rios");
        btUsuario.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/icones_desabilitados/usuario.png"))); // NOI18N
        btUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPessoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btEmbalagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(btProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(btUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPessoa)
                    .addComponent(btProduto)
                    .addComponent(btUnidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFornecedor)
                    .addComponent(btEmbalagem)
                    .addComponent(btUsuario))
                .addGap(5, 5, 5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)               
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Auxiliares", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Relat�rios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(522, 294));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorActionPerformed
        Fornecedores telaFornecedores = new Fornecedores();
        telaFornecedores.setVisible(true);
    }//GEN-LAST:event_btFornecedorActionPerformed

    private void btRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRequisicaoActionPerformed
        Requisicoes telaRequisicao = new Requisicoes();
        telaRequisicao.setVisible(true);
    }//GEN-LAST:event_btRequisicaoActionPerformed

    private void btCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCotacaoActionPerformed
        Cotacoes telaCotacao = new Cotacoes();
        telaCotacao.setVisible(true);
    }//GEN-LAST:event_btCotacaoActionPerformed

    private void btEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncomendaActionPerformed
        Encomendas telaEncomenda = new Encomendas();
        telaEncomenda.setVisible(true);
    }//GEN-LAST:event_btEncomendaActionPerformed

    private void btCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraActionPerformed
        Compras telaCompra = new Compras();
        telaCompra.setVisible(true);
    }//GEN-LAST:event_btCompraActionPerformed

    private void btPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPessoaActionPerformed
        Pessoas telaPessoas = new Pessoas();
        telaPessoas.setVisible(true);
    }//GEN-LAST:event_btPessoaActionPerformed

    private void btProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutoActionPerformed
        Produtos telaProdutos = new Produtos();
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_btProdutoActionPerformed

    private void btEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmbalagemActionPerformed
        Embalagens telaEmbalagens = new Embalagens();
        telaEmbalagens.setVisible(true);
    }//GEN-LAST:event_btEmbalagemActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        Usuarios telaUsuarios = new Usuarios();
        telaUsuarios.setVisible(true);
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnidadeActionPerformed
        UnidadesMedida telaUnidadesMedida = new UnidadesMedida();
        telaUnidadesMedida.setVisible(true);
    }//GEN-LAST:event_btUnidadeActionPerformed

    public static Principal getInstance(){ // M�TODO QUE VERIFICA SE A INSTANCIA J� EST� CRIADA (SINGLETON)
        if(instancia==null)
            instancia = new Principal();        
        return instancia;
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCompra;
    private javax.swing.JButton btCotacao;
    private javax.swing.JButton btEmbalagem;
    private javax.swing.JButton btEncomenda;
    private javax.swing.JButton btFornecedor;
    private javax.swing.JButton btPessoa;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btRequisicao;
    private javax.swing.JButton btUnidade;
    private javax.swing.JButton btUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
